# Run tests against developer push

# Runs jobs on linux and windows to maintain compatibility.

name: Build & run tests

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

jobs:
  build-test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '${{ matrix.node-version }}'

    - name: Install packages
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm run test
